/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSuperinvestorsIndexRouteImport } from './routes/_layout/superinvestors.index'
import { Route as LayoutAssetsIndexRouteImport } from './routes/_layout/assets.index'
import { Route as LayoutSuperinvestorsCikRouteImport } from './routes/_layout/superinvestors.$cik'
import { Route as LayoutAssetsCodeCusipRouteImport } from './routes/_layout/assets.$code.$cusip'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutSuperinvestorsIndexRoute =
  LayoutSuperinvestorsIndexRouteImport.update({
    id: '/superinvestors/',
    path: '/superinvestors/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutAssetsIndexRoute = LayoutAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutSuperinvestorsCikRoute = LayoutSuperinvestorsCikRouteImport.update({
  id: '/superinvestors/$cik',
  path: '/superinvestors/$cik',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAssetsCodeCusipRoute = LayoutAssetsCodeCusipRouteImport.update({
  id: '/assets/$code/$cusip',
  path: '/assets/$code/$cusip',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/superinvestors/$cik': typeof LayoutSuperinvestorsCikRoute
  '/assets': typeof LayoutAssetsIndexRoute
  '/superinvestors': typeof LayoutSuperinvestorsIndexRoute
  '/assets/$code/$cusip': typeof LayoutAssetsCodeCusipRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/superinvestors/$cik': typeof LayoutSuperinvestorsCikRoute
  '/assets': typeof LayoutAssetsIndexRoute
  '/superinvestors': typeof LayoutSuperinvestorsIndexRoute
  '/assets/$code/$cusip': typeof LayoutAssetsCodeCusipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/superinvestors/$cik': typeof LayoutSuperinvestorsCikRoute
  '/_layout/assets/': typeof LayoutAssetsIndexRoute
  '/_layout/superinvestors/': typeof LayoutSuperinvestorsIndexRoute
  '/_layout/assets/$code/$cusip': typeof LayoutAssetsCodeCusipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/superinvestors/$cik'
    | '/assets'
    | '/superinvestors'
    | '/assets/$code/$cusip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/superinvestors/$cik'
    | '/assets'
    | '/superinvestors'
    | '/assets/$code/$cusip'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/superinvestors/$cik'
    | '/_layout/assets/'
    | '/_layout/superinvestors/'
    | '/_layout/assets/$code/$cusip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/superinvestors/': {
      id: '/_layout/superinvestors/'
      path: '/superinvestors'
      fullPath: '/superinvestors'
      preLoaderRoute: typeof LayoutSuperinvestorsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/assets/': {
      id: '/_layout/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof LayoutAssetsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/superinvestors/$cik': {
      id: '/_layout/superinvestors/$cik'
      path: '/superinvestors/$cik'
      fullPath: '/superinvestors/$cik'
      preLoaderRoute: typeof LayoutSuperinvestorsCikRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/assets/$code/$cusip': {
      id: '/_layout/assets/$code/$cusip'
      path: '/assets/$code/$cusip'
      fullPath: '/assets/$code/$cusip'
      preLoaderRoute: typeof LayoutAssetsCodeCusipRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSuperinvestorsCikRoute: typeof LayoutSuperinvestorsCikRoute
  LayoutAssetsIndexRoute: typeof LayoutAssetsIndexRoute
  LayoutSuperinvestorsIndexRoute: typeof LayoutSuperinvestorsIndexRoute
  LayoutAssetsCodeCusipRoute: typeof LayoutAssetsCodeCusipRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSuperinvestorsCikRoute: LayoutSuperinvestorsCikRoute,
  LayoutAssetsIndexRoute: LayoutAssetsIndexRoute,
  LayoutSuperinvestorsIndexRoute: LayoutSuperinvestorsIndexRoute,
  LayoutAssetsCodeCusipRoute: LayoutAssetsCodeCusipRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
