/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const assetsTable = {
  name: "assets",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    cusip: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    asset: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    assetName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "asset_name",
    },
  },
  primaryKey: ["id"],
} as const;
const countersTable = {
  name: "counters",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    value: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const cusipQuarterInvestorActivityTable = {
  name: "cusipQuarterInvestorActivity",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    cusip: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    ticker: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    quarter: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    numOpen: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "num_open",
    },
    numAdd: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "num_add",
    },
    numReduce: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "num_reduce",
    },
    numClose: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "num_close",
    },
    numHold: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "num_hold",
    },
  },
  primaryKey: ["id"],
  serverName: "cusip_quarter_investor_activity",
} as const;
const entitiesTable = {
  name: "entities",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    category: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    value: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const mediumTable = {
  name: "medium",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const messageTable = {
  name: "message",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    senderId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "sender_id",
    },
    mediumId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "medium_id",
    },
    body: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    labels: {
      type: "json",
      optional: true,
      customType: null as unknown as string[],
    },
    timestamp: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const periodsTable = {
  name: "periods",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    period: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const searchesTable = {
  name: "searches",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    cusip: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    code: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    category: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const superinvestorsTable = {
  name: "superinvestors",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    cik: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    cikName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "cik_name",
    },
    cikTicker: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "cik_ticker",
    },
    activePeriods: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "active_periods",
    },
  },
  primaryKey: ["id"],
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    partner: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
  },
  primaryKey: ["id"],
} as const;
const userCountersTable = {
  name: "userCounters",
  columns: {
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    value: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["userId"],
  serverName: "user_counters",
} as const;
const valueQuartersTable = {
  name: "valueQuarters",
  columns: {
    quarter: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    value: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["quarter"],
  serverName: "value_quarters",
} as const;
const mediumRelationships = {
  messages: [
    {
      sourceField: ["id"],
      destField: ["mediumId"],
      destSchema: "message",
      cardinality: "many",
    },
  ],
} as const;
const messageRelationships = {
  sender: [
    {
      sourceField: ["senderId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  medium: [
    {
      sourceField: ["mediumId"],
      destField: ["id"],
      destSchema: "medium",
      cardinality: "one",
    },
  ],
} as const;
const userRelationships = {
  messages: [
    {
      sourceField: ["id"],
      destField: ["senderId"],
      destSchema: "message",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    assets: assetsTable,
    counters: countersTable,
    cusipQuarterInvestorActivity: cusipQuarterInvestorActivityTable,
    entities: entitiesTable,
    medium: mediumTable,
    message: messageTable,
    periods: periodsTable,
    searches: searchesTable,
    superinvestors: superinvestorsTable,
    user: userTable,
    userCounters: userCountersTable,
    valueQuarters: valueQuartersTable,
  },
  relationships: {
    medium: mediumRelationships,
    message: messageRelationships,
    user: userRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "assets" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Asset = Row<typeof assetsTable>;
/**
 * Represents a row from the "counters" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Counter = Row<typeof countersTable>;
/**
 * Represents a row from the "cusipQuarterInvestorActivity" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CusipQuarterInvestorActivity = Row<
  typeof cusipQuarterInvestorActivityTable
>;
/**
 * Represents a row from the "entities" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Entity = Row<typeof entitiesTable>;
/**
 * Represents a row from the "medium" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Medium = Row<typeof mediumTable>;
/**
 * Represents a row from the "message" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Message = Row<typeof messageTable>;
/**
 * Represents a row from the "periods" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Period = Row<typeof periodsTable>;
/**
 * Represents a row from the "searches" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Search = Row<typeof searchesTable>;
/**
 * Represents a row from the "superinvestors" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Superinvestor = Row<typeof superinvestorsTable>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<typeof userTable>;
/**
 * Represents a row from the "userCounters" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UserCounter = Row<typeof userCountersTable>;
/**
 * Represents a row from the "valueQuarters" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ValueQuarter = Row<typeof valueQuartersTable>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
